VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "FuturePosition"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
'#####################
Implements iPOSITION
'#####################

Private Sub iPOSITION_Init(Order_ As Sub402.iORDER, OpenDate_ As String, OpenPrice_ As String)

End Sub
Private Property Get iPOSITION_myStra() As Sub402.iSTRA

End Property
Private Property Get iPOSITION_OrderNO() As String

End Property
Private Property Get iPOSITION_Quantity() As String

End Property
Private Property Get iPOSITION_SerialNO() As String

End Property
Private Property Get iPOSITION_Status() As String

End Property
